-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 15:28:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema perry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema perry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `sedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedes` (
  `IDSEDE` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) CHARACTER SET 'utf8mb4'  NOT NULL,
  `CIUDAD` VARCHAR(60) NOT NULL,
  `DIRECCION` VARCHAR(100) NOT NULL,
  `HORARIOATENCION` VARCHAR(100) NOT NULL,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  `ESTADO` VARCHAR(10) NOT NULL,
  `IMGSEDE` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`IDSEDE`))

AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clases` (
  `IDCLASE` INT NOT NULL AUTO_INCREMENT,
  `IDSEDE` INT NOT NULL,
  `NOMBRECLASE` VARCHAR(50) NOT NULL,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  `HORARIOS` VARCHAR(100) NOT NULL,
  `IMGCLASES` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`IDCLASE`),
  INDEX `FK_clases_sedes` (`IDSEDE` ASC) ,
  CONSTRAINT `FK_clases_sedes`
    FOREIGN KEY (`IDSEDE`)
    REFERENCES `sedes` (`IDSEDE`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)

DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `IDSEDE` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_users_sedes` (`IDSEDE` ASC) ,
  CONSTRAINT `FK_users_sedes`
    FOREIGN KEY (`IDSEDE`)
    REFERENCES `sedes` (`IDSEDE`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)

AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras` (
  `IDCOMPRAS` INT NOT NULL AUTO_INCREMENT,
  `id` INT NULL DEFAULT NULL,
  `FECHACOMPRA` DATE NOT NULL,
  `METODOPAGO` VARCHAR(50) NOT NULL,
  `VALORCOMPRA` DECIMAL(20,6) NOT NULL,
  PRIMARY KEY (`IDCOMPRAS`),
  INDEX `FK_compras_users` (`id` ASC) ,
  CONSTRAINT `FK_compras_users`
    FOREIGN KEY (`id`)
    REFERENCES `users` (`id`))

DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `ropa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ropa` (
  `IDROPA` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `TIPO` VARCHAR(50) NOT NULL,
  `DESCRIPCION` VARCHAR(600) NOT NULL,
  `STOCK` INT NOT NULL,
  `PRECIO` DECIMAL(20,6) NOT NULL,
  `TALLA` VARCHAR(2) NOT NULL,
  `COLOR` VARCHAR(15) NOT NULL,
  `SEXO` VARCHAR(6) NOT NULL,
  `MATERIAL` VARCHAR(50) NOT NULL,
  `IMGPRENDA1` VARCHAR(100) NULL DEFAULT NULL,
  `IMGPRENDA2` VARCHAR(100) NULL DEFAULT NULL,
  `IMGPRENDA3` VARCHAR(100) NULL DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`IDROPA`))

AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `suplementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suplementos` (
  `IDSUPLEMENTO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) CHARACTER SET 'utf8mb4'  NOT NULL,
  `MARCA` VARCHAR(50) CHARACTER SET 'utf8mb4'  NOT NULL,
  `TIPO` VARCHAR(50) CHARACTER SET 'utf8mb4'  NOT NULL,
  `DESCRIPCION` VARCHAR(600) CHARACTER SET 'utf8mb4'  NOT NULL,
  `STOCK` INT NOT NULL,
  `PRECIO` DECIMAL(20,6) NOT NULL,
  `IMGSUPLEMENTO` VARCHAR(100) NULL DEFAULT NULL,
  `IMGTABLANUTRICIONAL` VARCHAR(100) NULL DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`IDSUPLEMENTO`))

AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `detallescompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detallescompras` (
  `IDDETALLESCOMPRAS` INT NOT NULL AUTO_INCREMENT,
  `IDSUPLEMENTO` INT NULL DEFAULT NULL,
  `IDROPA` INT NULL DEFAULT NULL,
  `IDCOMPRAS` INT NULL DEFAULT NULL,
  `UNIDADES` INT NOT NULL,
  `PRECIOUNITARIO` DECIMAL(20,6) NOT NULL,
  `TIPOPRODUCTO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDDETALLESCOMPRAS`),
  INDEX `FK_detallesCompras_compra` (`IDCOMPRAS` ASC) ,
  INDEX `FK_detallesCompras_ropa` (`IDROPA` ASC) ,
  INDEX `FK_detallesCompras_suplementos` (`IDSUPLEMENTO` ASC) ,
  CONSTRAINT `FK_detallesCompras_compra`
    FOREIGN KEY (`IDCOMPRAS`)
    REFERENCES `compras` (`IDCOMPRAS`),
  CONSTRAINT `FK_detallesCompras_ropa`
    FOREIGN KEY (`IDROPA`)
    REFERENCES `ropa` (`IDROPA`),
  CONSTRAINT `FK_detallesCompras_suplementos`
    FOREIGN KEY (`IDSUPLEMENTO`)
    REFERENCES `suplementos` (`IDSUPLEMENTO`))

DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elementos` (
  `IDELEMENTO` INT NOT NULL AUTO_INCREMENT,
  `IDSEDE` INT NOT NULL,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `TIPO` VARCHAR(50) NOT NULL,
  `USO` VARCHAR(100) NOT NULL,
  `FECHACOMPRA` DATE NOT NULL,
  `IMGELEMENTO` VARCHAR(100) CHARACTER SET 'utf8mb4'  NULL DEFAULT NULL,
  `SOPORTE` VARCHAR(500) NULL DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`IDELEMENTO`),
  INDEX `FK_elementos_sedes` (`IDSEDE` ASC) ,
  CONSTRAINT `FK_elementos_sedes`
    FOREIGN KEY (`IDSEDE`)
    REFERENCES `sedes` (`IDSEDE`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)

AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `espacios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `espacios` (
  `IDESPACIO` INT NOT NULL AUTO_INCREMENT,
  `IDSEDE` INT NOT NULL,
  `TIPO` VARCHAR(50) NOT NULL,
  `DESCRIPCION` VARCHAR(255) NOT NULL,
  `IMGESPACIO` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`IDESPACIO`),
  INDEX `FK_espacios_sedes` (`IDSEDE` ASC) ,
  CONSTRAINT `FK_espacios_sedes`
    FOREIGN KEY (`IDSEDE`)
    REFERENCES `sedes` (`IDSEDE`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)

DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `connection` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `queue` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `payload` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `exception` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) )

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquinas` (
  `IDEQUIPO` INT NOT NULL AUTO_INCREMENT,
  `IDSEDE` INT NOT NULL,
  `NOMBREMAQUINA` VARCHAR(50) NOT NULL,
  `GRUPOMUSCULAR` VARCHAR(50) NOT NULL,
  `FECHACOMPRA` DATE NOT NULL,
  `IMGMAQUINA` VARCHAR(100) NULL DEFAULT NULL,
  `SOPORTE` VARCHAR(500) NULL DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`IDEQUIPO`),
  INDEX `FK_maquinas_sedes` (`IDSEDE` ASC) ,
  CONSTRAINT `FK_maquinas_sedes`
    FOREIGN KEY (`IDSEDE`)
    REFERENCES `sedes` (`IDSEDE`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)

AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `tipomembresias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipomembresias` (
  `IDTIPOSMEMBRESIAS` INT NOT NULL AUTO_INCREMENT,
  `NOMBREMEMBRESIA` VARCHAR(100) CHARACTER SET 'utf8mb4'  NOT NULL,
  `DESCRIPCION` VARCHAR(255) CHARACTER SET 'utf8mb4'  NOT NULL,
  `PRECIO` DECIMAL(10,0) NOT NULL,
  `DURACIONMESES` INT NOT NULL,
  `PLANPAREJA` VARCHAR(2) CHARACTER SET 'utf8mb4'  NOT NULL DEFAULT '',
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`IDTIPOSMEMBRESIAS`))

AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `membresias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `membresias` (
  `IDMEMBRESIA` INT NOT NULL AUTO_INCREMENT,
  `id` INT NOT NULL,
  `id2` INT NULL DEFAULT NULL,
  `IDTIPOSMEMBRESIAS` INT NOT NULL,
  `FECHAMEMBRESIAINICIO` DATE NOT NULL,
  `FECHAMEMBRESIAFINAL` DATE NOT NULL,
  `MONTOPAGO` DECIMAL(10,0) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`IDMEMBRESIA`),
  INDEX `FK_membresias_users` (`id` ASC) ,
  INDEX `FK_membresias_users2` (`id2` ASC) ,
  INDEX `FK_tiposmembresias_membresias` (`IDTIPOSMEMBRESIAS` ASC) ,
  CONSTRAINT `FK_membresias_users`
    FOREIGN KEY (`id`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_membresias_users2`
    FOREIGN KEY (`id2`)
    REFERENCES `users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_tiposmembresias_membresias`
    FOREIGN KEY (`IDTIPOSMEMBRESIAS`)
    REFERENCES `tipomembresias` (`IDTIPOSMEMBRESIAS`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)

AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
;


-- -----------------------------------------------------
-- Table `migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))

AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `guard_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `model_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_has_permissions` (
  `permission_id` bigint unsigned NOT NULL,
  `model_type` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, -- Cambiado a varchar(191)
  `model_id` bigint unsigned NOT NULL,
  PRIMARY KEY (`permission_id`,`model_id`,`model_type`),
  KEY `model_has_permissions_model_id_model_type_index` (`model_id`,`model_type`),
  CONSTRAINT `model_has_permissions_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `guard_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`) )

AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `model_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_has_roles` (
  `role_id` BIGINT UNSIGNED NOT NULL DEFAULT '2',
  `model_type` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `model_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `model_id`, `model_type`),
  INDEX `model_has_roles_model_id_model_type_index` (`model_id` ASC, `model_type` ASC) ,
  CONSTRAINT `model_has_roles_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `roles` (`id`)
    ON DELETE CASCADE)

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `password_reset_tokens` (
  `email` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tokenable_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(64) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `abilities` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) )

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `role_has_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_has_permissions` (
  `permission_id` BIGINT UNSIGNED NOT NULL,
  `role_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `role_id`),
  INDEX `role_has_permissions_role_id_foreign` (`role_id` ASC) ,
  CONSTRAINT `role_has_permissions_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `role_has_permissions_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `roles` (`id`)
    ON DELETE CASCADE)

DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;



